// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK2hmR_wWMtQ2mHcgzt2OomjPjvjPyQAY',
    appId: '1:1085995317557:web:e044606423f96f249cb47c',
    messagingSenderId: '1085995317557',
    projectId: 'tareas-app-a43a5',
    authDomain: 'tareas-app-a43a5.firebaseapp.com',
    storageBucket: 'tareas-app-a43a5.appspot.com',
    measurementId: 'G-67JP2V6SRB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtW10pzO65OqJAZx-7_Dd27XzXk2M6-dM',
    appId: '1:1085995317557:android:d0e235fe7dcab1f59cb47c',
    messagingSenderId: '1085995317557',
    projectId: 'tareas-app-a43a5',
    storageBucket: 'tareas-app-a43a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANico7XyJNEEy5UEvyUHK854KPqhY-S58',
    appId: '1:1085995317557:ios:c0f357daad96f6ba9cb47c',
    messagingSenderId: '1085995317557',
    projectId: 'tareas-app-a43a5',
    storageBucket: 'tareas-app-a43a5.appspot.com',
    iosBundleId: 'com.example.tareasApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANico7XyJNEEy5UEvyUHK854KPqhY-S58',
    appId: '1:1085995317557:ios:c0f357daad96f6ba9cb47c',
    messagingSenderId: '1085995317557',
    projectId: 'tareas-app-a43a5',
    storageBucket: 'tareas-app-a43a5.appspot.com',
    iosBundleId: 'com.example.tareasApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBK2hmR_wWMtQ2mHcgzt2OomjPjvjPyQAY',
    appId: '1:1085995317557:web:3c75dc7ad7cab54e9cb47c',
    messagingSenderId: '1085995317557',
    projectId: 'tareas-app-a43a5',
    authDomain: 'tareas-app-a43a5.firebaseapp.com',
    storageBucket: 'tareas-app-a43a5.appspot.com',
    measurementId: 'G-B5TZ83DJ8B',
  );

}